/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import SE.componentes.Crud;
import SE.componentes.Fondo;
import SE.componentes.Hilo;
import SE.componentes.Validaciones;
import SE.componentes.Variables;
import SE.entidades.bloqueo;
import SE.views.matricula.cursos.MostrarCursosForm;
import SE.entidades.join.JoinEmpleados;
import SE.views.calificacion.CalificacionForm;
import SE.views.calificacion.ConductaGeneralMostrarForm;
import SE.views.complementos.datosInformacion;
import SE.views.empresa.MostrarEmpresaUnoForm;
import SE.views.empresa.sucursal.MostrarSucursalesForm;
import SE.views.empresa.MostrarInactivosForm;
import SE.views.materias.MostrarMateriasForm;
import SE.views.matricula.MostrarAlumnosForm;
import SE.views.matricula.MostrarMatriculasForm;
import SE.views.matricula.periodo.MostrarPeriodoForm;
import SE.views.mensualidades.MostrarMensualidadesForm;
import SE.views.precios.mostrarPreciosForm;
import SE.views.reportes.GraduadosReporteForm;
import SE.views.reportes.MostrarAlumnosReporteForm;
import SE.views.reportes.MostrarEmpleadosReportesForm;
import SE.views.reportes.PromedioReporteAlumnosTodosCalificacionForm;
import SE.views.reportes.ReporteAlumnosperiodoActualForm;
import SE.views.usuario.clave.ConfirmacionClaveForm;
import SE.views.usuario.empleados.MostrarEmpleadosForm;
import SE.views.usuario.empleados.NuevoEmpleadoDosForm;
import SE.views.usuario.empleados.PermisosMostrarEmpleadosForm;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author carlos
 */
public class FrmPrincipal extends javax.swing.JFrame {

    Variables fondo = new Variables();
    JoinEmpleados us = null;
    Hilo hilo;
    Crud c = new Crud();
    bloqueo b = new bloqueo();
    Validaciones val = new Validaciones();

    public FrmPrincipal(JoinEmpleados usuario) {
        initComponents();
        us = usuario;
        jmMensualidades.setVisible(false);
        jmPrecios.setVisible(false);
//        this.setTitle(fondo.getTitle() + TITLE + "---USUARIO" + " ---" + us.getNombre_comercial_em() + "---");
        this.add(new Fondo(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height), BorderLayout.CENTER);
        jToolBar1.setEnabled(false);
        this.setLocationRelativeTo(null);
        lbSucursal.setVisible(false);
        lbEmpresa.setVisible(false);
        lbIdUsuario.setVisible(false);
        this.setExtendedState(this.MAXIMIZED_BOTH);
//        this.setIconImage(fondo.getIconoVentana());
        System.out.println("usuario: " + usuario.getUsuario() + "   " + usuario.getId_usuario() + usuario.getId_empresa() + usuario.getId_sucursal());
        lbEmpresa.setText(us.getId_empresa().toString());
        lbSucursal.setText(us.getId_sucursal().toString());
        lbIdUsuario.setText(us.getId_usuario().toString());
        lbsuc.setText(us.getNombre_comercial_su());
        lbUsuario.setText(us.getUsuario());
        permisos();
        bloq();
        java.util.Date sistFecha = new java.util.Date();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");

        Timer tiempo = new Timer(100, new FrmPrincipal.horas());
        tiempo.start();

        fecha.setText(formato.format(sistFecha));
//        hilo = new Hilo(this);
//        hilo.start();
//        mens();
        
    }

    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        bloqCal = new javax.swing.JButton();
        bloqMat = new javax.swing.JButton();
        btnContra = new javax.swing.JButton();
        btnMatricula = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnCalificacion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbsuc = new javax.swing.JLabel();
        lbEmpresa = new javax.swing.JLabel();
        lbSucursal = new javax.swing.JLabel();
        lbIdUsuario = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meEmpresa = new javax.swing.JMenu();
        jmEmpresa = new javax.swing.JMenu();
        subEmpresa = new javax.swing.JMenuItem();
        subSucursales = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jmMensualidades = new javax.swing.JMenuItem();
        jmPrecios = new javax.swing.JMenuItem();
        jmUsuarios = new javax.swing.JMenuItem();
        jmPermisos = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        meMatricula = new javax.swing.JMenu();
        jmMatriculas = new javax.swing.JMenuItem();
        jmAlumnos = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        meCalificacion = new javax.swing.JMenu();
        jmCalificacion = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        meCursos = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        meMaterias = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        meReportes = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jmPerAnteriores = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jmEmpleados = new javax.swing.JMenuItem();
        jmGraduados = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bloqCal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bloqCal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado32sit.png"))); // NOI18N
        bloqCal.setText("DESACT.  CALIFICACION");
        bloqCal.setFocusable(false);
        bloqCal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bloqCal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bloqCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloqCalActionPerformed(evt);
            }
        });
        jToolBar1.add(bloqCal);

        bloqMat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bloqMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candado32sit.png"))); // NOI18N
        bloqMat.setText("DESACT. MATRICULA");
        bloqMat.setFocusable(false);
        bloqMat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bloqMat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bloqMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloqMatActionPerformed(evt);
            }
        });
        jToolBar1.add(bloqMat);

        btnContra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesDos/contra 32.png"))); // NOI18N
        btnContra.setText("  ACTUALIZAR  ");
        btnContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContra.setFocusable(false);
        btnContra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContra.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraActionPerformed(evt);
            }
        });
        jToolBar1.add(btnContra);

        btnMatricula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesDos/carpeta add 32.png"))); // NOI18N
        btnMatricula.setText("  MATRICULA  ");
        btnMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMatricula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMatricula.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatriculaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMatricula);

        btnUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dos_personas_32.png"))); // NOI18N
        btnUsuario.setText("  USUARIO  ");
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuario.setFocusable(false);
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsuario);

        btnCalificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCalificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesDos/lista 32.png"))); // NOI18N
        btnCalificacion.setText("  CALIFICACION  ");
        btnCalificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalificacion.setFocusable(false);
        btnCalificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalificacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCalificacion);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("USUARIO: ");

        lbUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbUsuario.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ESCUELA:");

        lbsuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbsuc.setText("   ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lbsuc, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbsuc)
                    .addComponent(jLabel1)
                    .addComponent(lbUsuario))
                .addContainerGap())
        );

        lbEmpresa.setText("empresa");

        lbSucursal.setText("sucursal");

        lbIdUsuario.setText("usuario");

        hora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hora.setText("jLabel2");
        hora.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        hora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hora.setVerifyInputWhenFocusTarget(false);

        fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setText("jLabel2");
        fecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 0, 0));
        mensaje.setText(" ");

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        meEmpresa.setText("MANTENIMIENTO");
        meEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meEmpresa.setMargin(new java.awt.Insets(3, 1, 3, 1));

        jmEmpresa.setText("EMPRESA");
        jmEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmEmpresa.setMargin(new java.awt.Insets(1, 0, 0, 0));

        subEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subEmpresa.setText("EMPRESA");
        subEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subEmpresaActionPerformed(evt);
            }
        });
        jmEmpresa.add(subEmpresa);

        subSucursales.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subSucursales.setText("SUCURSALES");
        subSucursales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subSucursalesActionPerformed(evt);
            }
        });
        jmEmpresa.add(subSucursales);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem11.setText("INACTIVOS");
        jMenuItem11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jmEmpresa.add(jMenuItem11);

        jmMensualidades.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmMensualidades.setText("MENSUALIDADES");
        jmMensualidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMensualidadesActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmMensualidades);

        jmPrecios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmPrecios.setText("PRECIOS");
        jmPrecios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPreciosActionPerformed(evt);
            }
        });
        jmEmpresa.add(jmPrecios);

        meEmpresa.add(jmEmpresa);

        jmUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmUsuarios.setText("USUARIOS");
        jmUsuarios.setBorderPainted(true);
        jmUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuariosActionPerformed(evt);
            }
        });
        meEmpresa.add(jmUsuarios);

        jmPermisos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmPermisos.setText("PERMISOS DE CURSOS");
        jmPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPermisosActionPerformed(evt);
            }
        });
        meEmpresa.add(jmPermisos);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem7.setText("ACTUALIZAR CLAVE");
        jMenuItem7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        meEmpresa.add(jMenuItem7);

        jMenuBar1.add(meEmpresa);

        meMatricula.setText("MATRICULA");
        meMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meMatricula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meMatricula.setMargin(new java.awt.Insets(3, 1, 3, 1));

        jmMatriculas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmMatriculas.setText("MATRICULAS");
        jmMatriculas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMatriculasActionPerformed(evt);
            }
        });
        meMatricula.add(jmMatriculas);

        jmAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmAlumnos.setText("ALUMNOS");
        jmAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumnosActionPerformed(evt);
            }
        });
        meMatricula.add(jmAlumnos);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem8.setText("PERIODO LECTIVO");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        meMatricula.add(jMenuItem8);

        jMenuBar1.add(meMatricula);

        meCalificacion.setText("CALIFICACION");
        meCalificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meCalificacion.setMargin(new java.awt.Insets(3, 1, 3, 1));

        jmCalificacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmCalificacion.setText("CALIFICACION");
        jmCalificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCalificacionActionPerformed(evt);
            }
        });
        meCalificacion.add(jmCalificacion);

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem12.setText("CONDUCTA GENERAL");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        meCalificacion.add(jMenuItem12);

        jMenuBar1.add(meCalificacion);

        meCursos.setText("CURSOS");
        meCursos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meCursos.setMargin(new java.awt.Insets(3, 1, 3, 1));

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem4.setText("CURSOS");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        meCursos.add(jMenuItem4);

        jMenuBar1.add(meCursos);

        meMaterias.setText("MATERIAS");
        meMaterias.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meMaterias.setMargin(new java.awt.Insets(3, 1, 3, 1));

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setText("MATERIAS");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        meMaterias.add(jMenuItem5);

        jMenuBar1.add(meMaterias);

        meReportes.setText("REPORTES");
        meReportes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        meReportes.setMargin(new java.awt.Insets(3, 1, 3, 1));

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem9.setText("CALIFICACION");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        meReportes.add(jMenuItem9);

        jmPerAnteriores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmPerAnteriores.setText("PERIODOS ANTERIORES");
        jmPerAnteriores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPerAnterioresActionPerformed(evt);
            }
        });
        meReportes.add(jmPerAnteriores);

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem16.setText("ALUMNOS");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        meReportes.add(jMenuItem16);

        jmEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmEmpleados.setText("EMPLEADOS");
        jmEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEmpleadosActionPerformed(evt);
            }
        });
        meReportes.add(jmEmpleados);

        jmGraduados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmGraduados.setText("GRADUADOS");
        jmGraduados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmGraduadosActionPerformed(evt);
            }
        });
        meReportes.add(jmGraduados);

        jMenuBar1.add(meReportes);

        jMenu3.setText("AYUDA");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(3, 1, 3, 1));

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem2.setText("INFORMACION");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setText("SALIR");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hora, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEmpresa)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbIdUsuario)
                                .addComponent(lbSucursal))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(lbEmpresa)
                .addGap(61, 61, 61)
                .addComponent(lbSucursal)
                .addGap(57, 57, 57)
                .addComponent(lbIdUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class horas implements ActionListener {

        public void actionPerformed(ActionEvent e) {

            java.util.Date sistHora = new java.util.Date();
            String pmAm = "HH:mm:ss";
            SimpleDateFormat format = new SimpleDateFormat(pmAm);
            java.util.Calendar hoy = java.util.Calendar.getInstance();
            hora.setText(String.format(format.format(sistHora), hoy));
        }
    }
    
    public void mens(){
        String msg = c.HiloStatement2();
        String salida="";
        if ("M1".equals(msg)) {
            salida="RENUEVE LA LICENCIA, QUEDAN CUATRO DIAS!";
        }
        if ("M2".equals(msg)) {
            salida="RENUEVE LA LICENCIA, QUEDAN TRES DIAS!";
        }
        if ("M3".equals(msg)) {
            salida="RENUEVE LA LICENCIA, QUEDAN DOS DIAS!";
        }
        if ("M4".equals(msg)) {
            salida="RENUEVE LA LICENCIA, QUEDAN UN DIA!";
        }
        mensaje.setText(salida);
    }

    public void bloq() {
        try {
//            bloqueo b = new bloqueo();
            b.setId_sucursal_bloqueo(us.getId_sucursal());
            String a = c.estadoMatricula(b);
            if ("a".equals(a)) {
                jmMatriculas.setEnabled(true);
                btnMatricula.setEnabled(true);
                bloqMat.setText("DESACT. MATRICULA");
            } else {
                jmMatriculas.setEnabled(false);
                btnMatricula.setEnabled(false);
                bloqMat.setText("ACT. MATRICULA");
            }

            String aa = c.estadoCalificacion(b);
            if ("a".equals(aa)) {
                jmCalificacion.setEnabled(true);
                btnCalificacion.setEnabled(true);
                bloqCal.setText("DESACT.  CALIFICACION");
            } else {
                jmCalificacion.setEnabled(false);
                btnCalificacion.setEnabled(false);
                bloqCal.setText("ACT.  CALIFICACION");
            }

        } catch (Exception e) {
            Logger.getLogger(Crud.class.getName()).log(Level.SEVERE, null, e);
        }

    }

    public void permisos() {
        String cargo = us.getRol();
        if ("ADMINISTRADOR".equals(cargo)) {

        } else {
            if ("RECTOR/A".equals(cargo)) {
                subEmpresa.setVisible(false);
                subSucursales.setVisible(false);
            }
            if ("INSPECTOR/A".equals(cargo)) {
                jmEmpresa.setVisible(false);
                bloqMat.setVisible(false);
                bloqCal.setVisible(false);
            }
            if ("PROFESOR/A".equals(cargo) || "PASANTE".equals(cargo)) {
                jmEmpresa.setVisible(false);
                jmPermisos.setVisible(false);
                jmUsuarios.setVisible(false);
                meMatricula.setVisible(false);
                btnMatricula.setVisible(false);
                btnUsuario.setVisible(false);
                meCursos.setVisible(false);
                meMaterias.setVisible(false);
                jmGraduados.setVisible(false);
                jmEmpleados.setVisible(false);
                jmPerAnteriores.setVisible(false);
                bloqMat.setVisible(false);
                bloqCal.setVisible(false);
            }
            if ("SECRETARIO/A".equals(cargo)) {
                jmEmpresa.setVisible(false);
                jmPermisos.setVisible(false);
                jmUsuarios.setVisible(false);
                btnUsuario.setVisible(false);
                btnCalificacion.setVisible(false);
                meCursos.setVisible(false);
                meMaterias.setVisible(false);
                jmAlumnos.setVisible(false);
                meCalificacion.setVisible(false);
                bloqMat.setVisible(false);
                bloqCal.setVisible(false);
            }
            if ("ESTUDIANTE".equals(cargo)) {
                meCalificacion.setVisible(false);
                meCursos.setVisible(false);
                meEmpresa.setVisible(false);
                meMaterias.setVisible(false);
                meMatricula.setVisible(false);
                meReportes.setVisible(false);
                bloqMat.setVisible(false);
                bloqCal.setVisible(false);
            }
        }
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int r = JOptionPane.showConfirmDialog(null, "¿DESEA SALIR DEL SISTEMA?", "", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        NuevoEmpleadoDosForm ne = new NuevoEmpleadoDosForm(new javax.swing.JFrame(), true, us);
        ne.setVisible(true);
    }//GEN-LAST:event_btnUsuarioActionPerformed


    private void jmUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuariosActionPerformed
        MostrarEmpleadosForm me = new MostrarEmpleadosForm(new javax.swing.JFrame(), true, us);
        me.setVisible(true);
    }//GEN-LAST:event_jmUsuariosActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ConfirmacionClaveForm cc = new ConfirmacionClaveForm(new javax.swing.JFrame(), true, us);
        cc.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        MostrarMateriasForm mm = new MostrarMateriasForm(new javax.swing.JFrame(), true, us);
        mm.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        MostrarCursosForm mc = new MostrarCursosForm(new javax.swing.JFrame(), true, us);
        mc.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        MostrarPeriodoForm mp = new MostrarPeriodoForm(new javax.swing.JFrame(), true, us);
        mp.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void subEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subEmpresaActionPerformed
        MostrarEmpresaUnoForm ae = new MostrarEmpresaUnoForm(new javax.swing.JFrame(), true, us);
        ae.setVisible(true);
    }//GEN-LAST:event_subEmpresaActionPerformed

    private void subSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subSucursalesActionPerformed
        MostrarSucursalesForm ms = new MostrarSucursalesForm(new javax.swing.JFrame(), true, us);
        ms.setVisible(true);
    }//GEN-LAST:event_subSucursalesActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        MostrarInactivosForm mi = new MostrarInactivosForm(new javax.swing.JFrame(), true, us);
        mi.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void btnContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraActionPerformed
        ConfirmacionClaveForm cc = new ConfirmacionClaveForm(new javax.swing.JFrame(), true, us);
        cc.setVisible(true);
    }//GEN-LAST:event_btnContraActionPerformed

    private void jmMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMatriculasActionPerformed
        MostrarMatriculasForm mm = new MostrarMatriculasForm(new javax.swing.JFrame(), true, us);
        mm.setVisible(true);
    }//GEN-LAST:event_jmMatriculasActionPerformed

    private void btnMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatriculaActionPerformed
        MostrarMatriculasForm mm = new MostrarMatriculasForm(new javax.swing.JFrame(), true, us);
        mm.setVisible(true);
    }//GEN-LAST:event_btnMatriculaActionPerformed

    private void jmAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumnosActionPerformed
        MostrarAlumnosForm ma = new MostrarAlumnosForm(new javax.swing.JFrame(), true, us);
        ma.setVisible(true);
    }//GEN-LAST:event_jmAlumnosActionPerformed

    private void jmPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPermisosActionPerformed
        PermisosMostrarEmpleadosForm pe = new PermisosMostrarEmpleadosForm(new javax.swing.JFrame(), true, us);
        pe.setVisible(true);
    }//GEN-LAST:event_jmPermisosActionPerformed

    private void jmCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCalificacionActionPerformed
        CalificacionForm ca = new CalificacionForm(new javax.swing.JFrame(), true, us);
        ca.setVisible(true);
    }//GEN-LAST:event_jmCalificacionActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        ReporteAlumnosperiodoActualForm ca = new ReporteAlumnosperiodoActualForm(new javax.swing.JFrame(), true, us);
        ca.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btnCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionActionPerformed
        CalificacionForm ca = new CalificacionForm(new javax.swing.JFrame(), true, us);
        ca.setVisible(true);
    }//GEN-LAST:event_btnCalificacionActionPerformed

    private void jmPerAnterioresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPerAnterioresActionPerformed
        PromedioReporteAlumnosTodosCalificacionForm rp = new PromedioReporteAlumnosTodosCalificacionForm(new javax.swing.JFrame(), true, us);
        rp.setVisible(true);
    }//GEN-LAST:event_jmPerAnterioresActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        MostrarAlumnosReporteForm mar = new MostrarAlumnosReporteForm(new javax.swing.JFrame(), true, us);
        mar.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jmEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEmpleadosActionPerformed
        MostrarEmpleadosReportesForm re = new MostrarEmpleadosReportesForm(new javax.swing.JFrame(), true, us);
        re.setVisible(true);
    }//GEN-LAST:event_jmEmpleadosActionPerformed

    private void jmGraduadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmGraduadosActionPerformed
        GraduadosReporteForm gr = new GraduadosReporteForm(new javax.swing.JFrame(), true, us);
        gr.setVisible(true);
    }//GEN-LAST:event_jmGraduadosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        datosInformacion di = new datosInformacion(new javax.swing.JFrame(), true);
        di.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void activarMatricula() {
        if ("DESACT. MATRICULA".equals(bloqMat.getText())) {
            b.setId_sucursal_bloqueo(us.getId_sucursal());
            c.estadoMatriculaDesact(b);

            jmMatriculas.setEnabled(false);
            btnMatricula.setEnabled(false);
            bloqMat.setText("ACT. MATRICULA");
        } else {
            b.setId_sucursal_bloqueo(us.getId_sucursal());
            c.estadoMatriculaAct(b);

            jmMatriculas.setEnabled(true);
            btnMatricula.setEnabled(true);
            bloqMat.setText("DESACT. MATRICULA");
        }
    }

    public void activarCalificacion() {
        if ("DESACT.  CALIFICACION".equals(bloqCal.getText())) {
            b.setId_sucursal_bloqueo(us.getId_sucursal());
            c.estadoCalificacionDesact(b);

            jmCalificacion.setEnabled(false);
            btnCalificacion.setEnabled(false);
            bloqCal.setText("ACT.  CALIFICACION");
        } else {
            b.setId_sucursal_bloqueo(us.getId_sucursal());
            c.estadoCalificacionAct(b);

            jmCalificacion.setEnabled(true);
            btnCalificacion.setEnabled(true);
            bloqCal.setText("DESACT.  CALIFICACION");
        }

    }

    private void bloqCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloqCalActionPerformed
        activarCalificacion();
    }//GEN-LAST:event_bloqCalActionPerformed

    private void bloqMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloqMatActionPerformed
        activarMatricula();
    }//GEN-LAST:event_bloqMatActionPerformed

    private void jmMensualidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMensualidadesActionPerformed
//        MostrarMensualidadesForm gr = new MostrarMensualidadesForm(new javax.swing.JFrame(), true, us);
//        gr.setVisible(true);
    }//GEN-LAST:event_jmMensualidadesActionPerformed

    private void jmPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPreciosActionPerformed
//        mostrarPreciosForm mp = new mostrarPreciosForm(new javax.swing.JFrame(), true, us);
//        mp.setVisible(true);
    }//GEN-LAST:event_jmPreciosActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        ConductaGeneralMostrarForm cg = new ConductaGeneralMostrarForm(new javax.swing.JFrame(), true, us);
        cg.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bloqCal;
    private javax.swing.JButton bloqMat;
    private javax.swing.JButton btnCalificacion;
    private javax.swing.JButton btnContra;
    private javax.swing.JButton btnMatricula;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jmAlumnos;
    private javax.swing.JMenuItem jmCalificacion;
    private javax.swing.JMenuItem jmEmpleados;
    private javax.swing.JMenu jmEmpresa;
    private javax.swing.JMenuItem jmGraduados;
    private javax.swing.JMenuItem jmMatriculas;
    private javax.swing.JMenuItem jmMensualidades;
    private javax.swing.JMenuItem jmPerAnteriores;
    private javax.swing.JMenuItem jmPermisos;
    private javax.swing.JMenuItem jmPrecios;
    private javax.swing.JMenuItem jmUsuarios;
    private javax.swing.JLabel lbEmpresa;
    private javax.swing.JLabel lbIdUsuario;
    private javax.swing.JLabel lbSucursal;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbsuc;
    private javax.swing.JMenu meCalificacion;
    private javax.swing.JMenu meCursos;
    private javax.swing.JMenu meEmpresa;
    private javax.swing.JMenu meMaterias;
    private javax.swing.JMenu meMatricula;
    private javax.swing.JMenu meReportes;
    private javax.swing.JLabel mensaje;
    private javax.swing.JMenuItem subEmpresa;
    private javax.swing.JMenuItem subSucursales;
    // End of variables declaration//GEN-END:variables
}
